# Generated by Django 5.0.14 on 2026-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(default='#FFD700', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='easy', max_length=10)),
                ('weekdays', models.JSONField(default=list)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('repeat', models.CharField(choices=[('none', 'Без повтора'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='none', max_length=20)),
                ('is_group', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('monster_sprite', models.CharField(choices=[('slime', 'Слизень'), ('bat', 'Летучая мышь'), ('skeleton', 'Скелет'), ('orc', 'Орк'), ('dragon', 'Дракон'), ('goblin', 'Гоблин')], default='slime', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_time', 'difficulty'],
            },
        ),
    ]
