# Generated by Django 5.0.14 on 2026-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('damage_dealt', models.PositiveIntegerField(default=0)),
                ('victory', models.BooleanField(default=False)),
                ('exp_gained', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
